mariadb:
  image: mariadb
  environment:
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: dbpassword
    MYSQL_ROOT_PASSWORD: dbrootpassword
    MYSQL_DATABASE: dbdatabase
  ports:
    - 6603:3306
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mariadb
  environment:
    PMA_HOST: mariadb
    PMA_PORT: 3306
  ports:
    - '8080:80'