<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $email
     * @return array
     */
    public function getSimpleResultFromEmail(string $email) : array
    {
        return $this
            ->createQueryBuilder('p')
            ->select('1')
            ->where('p.email = :email')
            ->setParameter('email', $email)
            ->getQuery()
            ->getResult();
    }
}
